### ISSUE TITLE
Open to a stackage release?

### ISSUE THREAD

**Issue by MichaelXavier** [plow-technologies/quickcheck-arbitrary-template#5]
Curious if you're open to a stackage release. I'm using this package and stackage can't run tests against my package without this. I'd be willing to pitch in if that would persuade you.

**Comment by mchaver** [comment]
@MichaelXavier Sure, I think we are fine with that. I'll take care of it over the weekend.

**Comment by MichaelXavier** [comment]
Just following up on this. Haven't seen the library show up yet. Thanks!

**Comment by MichaelXavier** [comment]
Just bumping again. I really hate that the stackage process sort of compels package maintainers to be pests to get things unblocked, but I'd really like to get a few of my packages back into the LTS.

**Comment by smurphy8** [comment]
@mchaver do you think you have time for this?

**Comment by MichaelXavier** [comment]
Pinging this again.

**Comment by bitemyapp** [comment]
@smurphy8 @mchaver ping

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for quickcheck-arbitrary-template-0.2.0.0:
    template-haskell-2.14.0.0 from stack configuration does not
                              match >=2.11 && <2.13  (latest matching version
                              is 2.12.0.0)
needed due to bloodhound-0.16.0.0 -> quickcheck-arbitrary-template-0.2.0.0

Some different approaches to resolving this:

  * Set 'allow-newer: true'
    in /home/callen/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps
    in /home/callen/work/bloodhound/stack-8.6.yaml:
```

Gonna be forking to resolve this so I can get rolling with 8.6 in Bloodhound.

**Comment by mchaver** [comment]
It's only taken me one year.
https://github.com/commercialhaskell/stackage/pull/4745

**Comment by smurphy8** [comment]
Thanks @mchaver !

**Comment by bitemyapp** [comment]
@mchaver thank you!
